# Generated by Django 2.0.2 on 2018-11-17 23:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('globee', '0002_auto_20180727_0214'),
    ]

    operations = [
        migrations.AlterField(
            model_name='globeeipn',
            name='custom_payment_id',
            field=models.CharField(help_text='A reference or custom identifier that you can use to link the payment back to your system', max_length=255, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='globeeipn',
            name='payment_id',
            field=models.CharField(help_text='Globee payment ID', max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='globeeipn',
            name='payment_status',
            field=models.CharField(choices=[('unpaid', 'unpaid - ready to receive payment'), ('paid', 'waiting for confirmations'), ('underpaid', 'user has paid less'), ('overpaid', 'user has mistakenly paid more'), ('paid_late', 'the payment was made outside of the quotation window'), ('confirmed', 'payment has been confirmed'), ('completed', 'payment-request is now completed')], default='unpaid', help_text='Globee payment status', max_length=12),
        ),
    ]
