# Generated by Django 2.0.2 on 2018-11-17 20:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('globee', '0002_auto_20180727_0214'),
    ]

    operations = [
        migrations.AlterField(
            model_name='globeeipn',
            name='custom_payment_id',
            field=models.CharField(help_text='A reference or custom identifier that you can use to link the payment back to your system', max_length=255, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='globeeipn',
            name='payment_id',
            field=models.CharField(help_text='Globee payment ID', max_length=255, unique=True),
        ),
    ]
