# Generated by Django 2.0.2 on 2018-11-17 22:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('globee', '0003_auto_20181117_2107'),
    ]

    operations = [
        migrations.AlterField(
            model_name='globeeipn',
            name='payment_status',
            field=models.CharField(
                choices=[
                    ('unpaid', 'unpaid - ready to receive payment'),
                    ('paid', 'waiting for confirmations'),
                    ('underpaid', 'user has paid less'),
                    ('overpaid', 'user has mistakenly paid more'),
                    ('paid_late', 'the payment was made outside of the quotation window'),
                    ('confirmed', 'payment has been confirmed'),
                    ('completed', 'payment-request is now completed')
                ],
                default='unpaid',
                help_text='Globee payment status',
                max_length=12),
        ),
    ]
