dist: xenial
language: python
python:
- '3.5'
- '3.6'
- '3.7'
env:
  matrix:
  - DJANGO=2.0 DB=sqlite
  - DJANGO=2.1 DB=sqlite
install:
- pip install -q Django==$DJANGO
- pip install python-coveralls
- pip install coverage
- python setup.py -q install
- django-admin.py startproject my_proj .
- cp --remove-destination test_settings.py my_proj/settings.py
- python manage.py migrate
script:
- python manage.py test globee
- coverage run --source=globee manage.py test globee
- coverage report -m
after_success:
- coveralls
